-- Supabase schema for VIRTVS Drop I early-access signups.
-- Run this in Supabase SQL Editor before setting production env vars.

create table if not exists public.drop_i_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  phone text,
  preference text not null default 'both' check (preference in ('hoodie', 'hat', 'both')),
  source text not null default 'virtvs-drop-i-landing',
  user_agent text,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists drop_i_signups_created_at_idx
  on public.drop_i_signups (created_at);

create index if not exists drop_i_signups_unsubscribed_at_idx
  on public.drop_i_signups (unsubscribed_at);

alter table public.drop_i_signups enable row level security;

-- No public browser access is needed. The Next.js API route writes with the
-- server-only SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
